<a href="https://colab.research.google.com/github/kIaptuk/PYTHON_TASKS/blob/main/%D0%92%D0%B8%D0%BA%D0%BE%D0%BD%D0%B0%D0%BD%D0%BD%D1%8F_%D0%B7%D0%B0%D0%B2%D0%B4%D0%B0%D0%BD%D0%BD%D1%8F_13_%22hw_10_3_%D0%A0%D0%BE%D0%B7%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D1%96_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B8_%D0%BE%D0%B1%D1%80%D0%BE%D0%B1%D0%BA%D0%B8_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85_%D1%83_Pandas_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнє завдання до теми "Розширені методи обробки даних у Pandas"

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [4]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('drive/MyDrive/CSV_Data/supermarket_sales.csv')

Mounted at /content/drive

1. Відсортуйте дані за спаданням ціни товара ('Unit price') і виведіть 5 перших рядочків на екран.

In [ ]:
df.sort_values(['Unit price'], ascending = [False]).head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
983,148-41-7930,C,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.986,734.706,1/23/2019,10:33,Cash,699.72,4.761905,34.986,6.1
122,219-22-9386,B,Mandalay,Member,Male,Sports and travel,99.96,9,44.982,944.622,3/9/2019,17:26,Credit card,899.64,4.761905,44.982,4.2
930,641-62-7288,B,Mandalay,Normal,Male,Home and lifestyle,99.92,6,29.976,629.496,3/24/2019,13:33,Ewallet,599.52,4.761905,29.976,7.1
494,437-53-3084,B,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.989,209.769,2/26/2019,11:48,Ewallet,199.78,4.761905,9.989,7.1
283,667-92-0055,A,Yangon,Member,Male,Health and beauty,99.83,6,29.949,628.929,3/4/2019,15:02,Ewallet,598.98,4.761905,29.949,8.5

2. Знайдіть інвойс (рядок в даних) в категорії товарів `Electronic accessories`, в якому був куплений товар з найбільшою кількістю і найбільшою ціною. Виведіть цей рядок даних на екран.

In [ ]:
df.query('`Product line` == "Electronic accessories" ').sort_values(['Quantity', 'Unit price']).tail(1)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
105,704-48-3927,A,Yangon,Member,Male,Electronic accessories,88.67,10,44.335,931.035,1/12/2019,14:50,Ewallet,886.7,4.761905,44.335,7.3

3.1. Створіть нову колонку в даних `Rating Category`, яка визначає категорію рейтингу (`Rating`): високий, середній чи низький за наступним правилом:
- якщо рейтинг вищий або рівний 8 - то він високий (`High`)
- якщо рейтинг від 6 (включно) до 8 (не включно) - то він середній (`Medium`)
- інакше - низький (`Low`).

In [6]:
def rating_values(rate):
  if rate >= 8:
    return "High"
  elif 8 > rate >= 6:
    return "Medium"
  else:
    return "low"

df['Rating Category'] = df.Rating.apply(rating_values)
df[['Rating','Rating Category']].head()

   Rating Rating Category
0     9.1            High
1     9.6            High
2     7.4          Medium
3     8.4            High
4     5.3             low

3.2. Виведіть, який відсоток даних становить кожне зі значень категорій рейтингу.

In [13]:
(df.value_counts('Rating Category')/df.value_counts('Rating Category').sum())*100

Rating Category
Medium    35.6
High      32.9
low       31.5
Name: count, dtype: float64

4.1. Запустіть код нижче аби створити змінну `time`. Ця змінна містить час в форматі "година:хвилина". Напишіть функцію `get_hour`, яка буде зі змінної формату як `time` дістати лише години і конвертувати їх у тип `int`.

Запустіть написану функцію на змінній `time` та перевірте правильність роботи функції.

In [14]:
time = '11:28'

In [20]:
def get_hour(value):
  return int(value[0:2])
type(get_hour(time))

int

4.2. З допомогою функції `get_hour` і метода `DataFrame.apply()` створіть нову колонку `Hour` в нашому наборі даних, яка буде містити години здійснення покупки, обчислені на основі часу здійснення покупки `Time`.

In [22]:
df['Hour']= df.Time.apply(get_hour)
df[['Time','Hour']].head()

    Time  Hour
0  13:08    13
1  10:29    10
2  13:23    13
3  20:33    20
4  10:37    10

4.3. Виведіть кількість значень за кожною годиною покупки і дайте відповідь "О яких годинах найбільше здійснюють покупок покупці і чому на Ваш погляд саме о цих годинах? Чи це слогічно, що найбільше покупок саме в ці години?".

In [24]:
df.value_counts('Hour')

Hour
19    113
13    103
15    102
10    101
18     93
11     90
12     89
14     83
16     77
20     75
17     74
Name: count, dtype: int64

Найбільше покупок здійснюється в 19, 13, 15 і 10 годинах. Хоч їхнє співвідношення є доволі хаотичним, я впевнений що 19 година має найбільше продажів через те, що на той момент година роботи споживача вже закінчилася і це надає йому змогу відвідати магазин. 13, 15 і 10 години мають майже ідентичну кількість відвідувань між собою, коли 12, 14 і 11 мають набагато менше, хоч вони відбуваються поміж даних годин. 10 годину можна спробувати пояснити подібно до 19, тобто що ще не час роботи для більшості користувачів, коли 13 і 15 складніше пояснити. Єдине що можна теоризувати це спеціальні акції в магазинах на ці години, або логістична зручність певних користувачів саме на той час.

5. Виведіть середнє значення чеку (`Total`) для покупок в містах, наявних в даних, за допомогою функції `groupby`.

In [25]:

df.groupby('City')['Total'].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Total, dtype: float64

6. Виведіть кількість покупок, середнє, мінімальне та максимальне значення для загальної суми чеку (Total) в містах, наявних в даних, за допомогою функції groupby.
Зробіть висновки з цих показників та дайте рекомендації для мережі супермаркетів.

In [28]:
df.groupby('City')['Total'].agg(['mean','min','max'])

                 mean      min      max
City
Mandalay   319.872506  18.6375  1022.49
Naypyitaw  337.099715  10.6785  1042.65
Yangon     312.354031  12.6945  1039.29

З даних міст Naypyitaw має найбільше середнє значення, найменше мінімальне значення і найбільше максимальне. З даних виходить що це є найбільш пробутковий з трьох міст, навіть якщо співвідношення мвксимуму та мінімуму є найбільшим. Хоч є імовірність вкидів, середнє значення в даному випадку має значення, тому іншим менеджменту магазинів двох інштх міст варто перевірити які методи  менеджменту Naypyitaw використовуюють щоб можливо підвищити свій прибуток також.

7. Ми внесли деякі зміни в наш набір даних, тож, давайте запишемо результат у файл. Запишіть оновлену версію даних у файл `supermarket_sales_enriched.csv`. Зверніть увагу, аби не записати нічого зайвого, наприклад, індекси рядків нам в файлі не потрібні, оскільки вони стандартні.

In [29]:
df.to_csv('supermarket_sales_enriched.csv', index = False)