<a href="https://colab.research.google.com/github/kIaptuk/PYTHON_TASKS/blob/main/%D0%92%D0%B8%D0%BA%D0%BE%D0%BD%D0%B0%D0%BD%D0%BD%D1%8F_%D0%B7%D0%B0%D0%B2%D0%B4%D0%B0%D0%BD%D0%BD%D1%8F_14_%22hw_10_4_apply%2C_groupby%2C_pivot_table_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('drive/MyDrive/CSV_Data/supermarket_sales.csv')

Mounted at /content/drive

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [4]:
df.groupby(["Branch"])['gross income'].sum()

Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [5]:
df.groupby(["Branch","City"])['gross income'].sum()

Branch  City
A       Yangon       5057.1605
B       Mandalay     5057.0320
C       Naypyitaw    5265.1765
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [36]:
invoices_by_category = df.pivot_table(index = "Branch", columns = 'Product line', values = 'City',  aggfunc= 'count')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [44]:
invoices_by_category["Electronic accessories"].idxmax()

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

Крок 1.ТРИ питання (гіпотези):
1.  Як стать покупця впливає на тип продукції яку вони купляють (Перевірити співвідношення типу продукції до гендеру покупця у формі загального прибутку та кількості транзакцій щоб зрозуміти закономірність)
2.  Який з підрозділів магазину має найнищий рейтинг і якщо це критично -як вирішити?(Визначити середній рівень рейтингу в різних розділах)
3. Як тип оплати є пов'язаним з типом користувача через membership card і як цим можна скористуватися (Визначити співвідношення типу оплати до типу користувачів через середнє значення)

## Крок 2 Знайдіть відповіді на свої питання##
Спочатку визначається співвідношення гендеру покупця до прибутку

In [49]:

df.pivot_table(index = "Gender", columns = 'Product line', values = 'gross income',  aggfunc= 'sum')

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,1290.5725,1449.400,1579.5675,883.8565,1430.3275,1360.7010
Male,1296.9290,1136.595,1093.9965,1458.7025,1134.5255,1264.1955

Де співвідношення в кількості дорівнює:

In [50]:
df.pivot_table(index = "Gender", columns = 'Product line', values = 'gross income',  aggfunc= 'count')

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,84,96,90,64,79,88
Male,86,82,84,88,81,78

Далі шукається співвідношення рейтингу

In [60]:
df.groupby('Branch')['Rating'].mean()

Branch
A    7.027059
B    6.818072
C    7.072866
Name: Rating, dtype: float64

І під кінець - середнє значення з типу оплати

In [63]:
df.pivot_table(index = "Customer type", columns = 'Payment', values = 'gross income',  aggfunc= 'sum')

Payment             Cash  Credit card   Ewallet
Customer type
Member         2602.9055    2751.0225  2466.236
Normal         2740.2645    2047.4095  2771.531

In [64]:
df.pivot_table(index = "Customer type", columns = 'Payment', values = 'gross income',  aggfunc= 'count')

Payment        Cash  Credit card  Ewallet
Customer type
Member          168          172      161
Normal          176          139      184

Крок 3. Напишіть, як відповідь на це питання може бути використана

1. З даного результату можна задати спеціальні таргетовані реклами для користувачів які є більш зацікавленні в даній продукції ніж інша  
2. З рейтингу видно що Branch B має помітно нище середнє значення, можливо варто провести аналіз чому користувачі в даній локації є менш задоволенні ніж в інших  
3. Можна провести спеціальні колаборації з методами проведедення транзакій щоб заохочувати member користувачів чи можливо надавати пропозиції для звичайних користувачів для отримання membership